### ISSUE TITLE
Cities aren't linked to counties

### ISSUE THREAD

**Issue by bmoji97** [megan240/oregoninvasiveshotline#6]
## Cities table does not contain a Counties element
With the current implementation of the cities table in the db, cities have a name as the primary key and a state. Ideally the cities table also contains a foreign key entry to the county the city is in.

**Comment by bmoji97** [comment]
Also, currently the bootstrapper would fail when first setting up the database since there is no city data or city links to reports provided

**Comment by sfletcher15** [comment]
> Also, currently the bootstrapper would fail when first setting up the database since there is no city data or city links to reports provided

This is fixed by creating and migrating the model. I'll update the wiki with the proper instructions.
